MarketMaven/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace MarketMaven.Models
{
    public class Employee
    {
        // Implement code here
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter the email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter the name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please re-enter the password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Please enter the age")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Please enter the contact details")]
        public long Contact { get; set; }
    }
}
	 	  	  		    	  	   	    	 	

MarketMaven/Models/EmployeeLogin.cs
using System.ComponentModel.DataAnnotations;

namespace MarketMaven.Models
{
    public class EmployeeLogin
    {
        // Implement code here
        [Required(ErrorMessage = "Please enter the email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter the password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

MarketMaven/Models/ErrorViewModel.cs
namespace MarketMaven.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarketMaven/Models/MarketDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace MarketMaven.Models
{
    public class MarketDBContext : DbContext
    {
        public MarketDBContext(DbContextOptions<MarketDBContext> options) : base(options)
        {

        }

        // Implement code here
        public DbSet<Employee> Employees { set; get; }
    }
}

MarketMaven/Controllers/MarketController.cs
using MarketMaven.Models;
using Microsoft.AspNetCore.Mvc;

namespace MarketMaven.Controllers
{
    public class MarketController : Controller
    {
        // Implement code here
        MarketDBContext dbContext;
        public MarketController(MarketDBContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult RegisterForm()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterForm(EmployeeLogin login)
        {
            if (ModelState.IsValid)
            {
                var r = dbContext.Employees.Where
                        (l => l.Email == login.Email).FirstOrDefault();

                if (r != null)
                    return RedirectToAction("GreetNote", login);

                return View();
            }
            return View();
        }

        public IActionResult AddEmployee()
        {
            return View();
        }	 	  	  		    	  	   	    	 	

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEmployee(Employee employee)
        {
            if (ModelState.IsValid)
            {
                if (employee.Email == employee.Password)
                {
                    ViewBag.Message = "Email and Password should not be the same";
                }
                else
                {
                    dbContext.Employees.Add(employee);
                    dbContext.SaveChanges();
                    return RedirectToAction("RegisterForm");
                }

                return View();
            }

            return View();
        }

        public IActionResult GreetNote(EmployeeLogin model)
        {
            return View(model);
        }
    }
}
	 	  	  		    	  	   	    	 	

MarketMaven/Views/Market/AddEmployee.cshtml
<!-- Implement code here -->
@model MarketMaven.Models.Employee

@{
    ViewData["Title"] = "AddEmployee";
}

<h1>AddEmployee</h1>

<hr />
@{
    <h2>@ViewBag.Message</h2>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEmployee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="btnSubmit" type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {	 	  	  		    	  	   	    	 	
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarketMaven/Views/Market/GreetNote.cshtml
<!-- Implement code here -->

@model MarketMaven.Models.EmployeeLogin

@{
    ViewData["Title"] = "GreetNote";
}

@{
    <h1 id="message">Welcome to Market Maven - @Model.Email</h1>
}

<div>
    <a asp-controller="Market"  asp-action="RegisterForm">Back to Login page</a>
</div>

MarketMaven/Views/Market/RegisterForm.cshtml
<!-- Implement code here -->
@model MarketMaven.Models.EmployeeLogin

@{
    ViewData["Title"] = "RegisterForm";
}

<h1>RegisterForm</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RegisterForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="btnLogin" value="Login" class="btn btn-primary" />
                <a id="lnkRegister" asp-controller="Market" asp-action="AddEmployee">Register</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {	 	  	  		    	  	   	    	 	
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarketMaven/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarketMaven</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarketMaven.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarketMaven</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MarketMaven - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
	 	  	  		    	  	   	    	 	